### ISSUE TITLE
Prevent -128 movement

### ISSUE THREAD

**Issue by iznogod** [opencj-dev/server-gsc#117]
what about ele scripts?

**Comment by opencj-dev** [comment]
force to (-)127 and push a callback

**Comment by Yocairo** [comment]
move.forward + move.right

**Comment by Yocairo** [comment]
perhaps callback

**Comment by Yocairo** [comment]
Doesn't seem to have effect, but that's because I think CoD4x server already has it properly patched in MSG_ReadForwardRightMove

Patched in libcod just in case it wasn't patched there yet.
