### ISSUE TITLE
Better commands and settings system

### ISSUE THREAD

**Issue by iznogod** [opencj-dev/server-gsc#128]

**Comment by iznogod** [comment]
aliases
non-arg funcs
on/off/true/false/0/1
registercommandbool
showhelpforfunc()
adminlevel based availability (new column in playerInformation table)

**Comment by iznogod** [comment]
Push to databse.

for bool vars: toggle as value.

**Comment by iznogod** [comment]
Subcommands also supported somehow !huds record shownades on

**Comment by Yocairo** [comment]
will make this tomorrow, we gotta discuss the db side of things though.

**Comment by Yocairo** [comment]
[x] aliases
[x] non-arg funcs
[x] on/off/true/false/0/1
[x] registercommandbool
[x] showhelpforfunc()
[prepared but no db changes yet] adminlevel based availability (new column in playerInformation table)
[forgot, but do we want this for every command??] /commands (currently only !commands)
[x] commandlist (in help?)
[will be in new ticket] Push to databse.
[x] for bool vars: toggle as value.
[it's just a command with arguments] Subcommands also supported somehow !huds record shownades on
