### ISSUE TITLE
Stock map classname cleanup (MG42, bomb thingies etc)

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#13]

**Comment by iznogod** [comment]
Please dont purge stuff to "dm", i think "sd" should be better (have bombsites to bounce off of). Unsure about the exact wording.

Also, please purge all pickupables (maybe including map-based weapons on ending the map that use a trigger_use_touch?)

**Comment by Yocairo** [comment]
"maybe including map-based weapons on ending the map that use a trigger_use_touch?"
Not including that, because this ticket is about stock maps
