### ISSUE TITLE
Custom openCJ minimap if map doesn't have one already

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#134]
- Shouldn't be a trash custom texture, if map doesn't have one, use a default
- Angles need to be correct (getnorthyaw)

**Comment by fnkcj** [comment]
Some maps have custom minimaps that work fine and fit the theme of the map (see newest version of mp_mody_v4), so I think a discussion should be had whether we want to just force replace every map or only selected maps. 

Though I admit in terms of branding and style, a consistent minimap is probably better.

**Comment by Yocairo** [comment]
Is a discussion needed? I would say always use map if they have a custom one, otherwise use our openCJ default.

**Comment by iznogod** [comment]
If the default one for the map is trash we could also consider replacing it, otherwise as per ridge imo

**Comment by Yocairo** [comment]
Is there a way to know if the map has a minimap image, though? As in, programmatically? Or will we just put a default minimap image in the mod, and let map ones override it?

**Comment by iznogod** [comment]
Do we know any maps with minimap image to check what's being called so we can check in server mem if it isset?

**Comment by fnkcj** [comment]
Newest version of mp_mody_v4 has a custom minimap. You can download the map [here](https://fnkcj.github.io/mp_mody_v4).

**Comment by iznogod** [comment]
cod2 doesnt have minimaps on compass, only a background that's themeable but does not scroll (unsure about rotate)

**Comment by Yocairo** [comment]
iwi that funk sends me results in default texture, so need figure that out next time
