### ISSUE TITLE
Add commands: kick, ban, tignore (=ignore), fignore (=permignore), tmute (=mute), fmute (=permmute)

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#144]

**Comment by fnkcj** [comment]
Can the commands be streamlined? I feel like we are going to reach a point where we will have a million different commands so would be great if we could combine some of them together in an early stage. Personally I don't think we need 2 different commands for perm/temp mute and same for ignore. How about:

```
!mute <player> <duration>
!ignore <player> <duration>
```

...where `<duration>` is an optional parameter. If it's not included it will be permanent and if it is then it's going to be temporary.

Also obviously we need a way to undo these actions, so:

```
!unmute <player>
!unignore <player>
```

**Comment by Yocairo** [comment]
I don't like having a mute command that can accidentally permanently mute someone if you forget an argument.
Same for ignore. Which is why I intentionally made two commands. However, the users will not notice this, because aliases do not show up in !help

**Comment by iznogod** [comment]
Maybe we can add forever as the time, and a default time when no argument is given.

**Comment by iznogod** [comment]
ignore, pignore and unignore added.

**Comment by iznogod** [comment]
mute and unmute added. Mute has [time] as second argument, format [m]inutes, [h]ours or [d]ays. Max muted time is 7d. Do not mix times (ie !mute player 3h3d does not work, just use !mute player 3d)
