### ISSUE TITLE
Loading when in spectator should put you ingame at your last saved position

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#147]

**Comment by iznogod** [comment]
loadbind only or double f too?

**Comment by Yocairo** [comment]
I'm not sure what 3xP does, maybe noob or funk can elaborate

**Comment by Yocairo** [comment]
Only load bind

**Comment by Yocairo** [comment]
Implemented for free spec, need another person sometime to test without free spec (currently not implemented, it's just removing a check though)

**Comment by Yocairo** [comment]
Implemented
