### ISSUE TITLE
Server crash on mp_the_extreme and mp_legacy and mp_atlantis

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#166]
![image](https://user-images.githubusercontent.com/26691621/186213999-a915f169-d344-4b47-b2d4-c5bd4b2b9453.png)

Occurred when Funk noclipped to the player model room.
Missing stock function called by map gsc or something?

**Comment by iznogod** [comment]
these are stock function calls set inside of the suicide function it seems. is killtriggers.gsc a stock file or is it inside theextreme?

On stock scripts level.spectator is set to the func that is also called when you click "spectate" in the menu. Unsure if this would be a good fit to do here, or if it should just be a suicide() call when player is not noclipping.

**Comment by Yocairo** [comment]
killtriggers.gsc is part of mp_the_extreme. It calls:

player [[level.spectator]]();
player [[level.allies]]();

I think a suicide when not noclipping should be fine, but at the same time these are the kind of map scripts I would be keen to purge.

**Comment by Yocairo** [comment]
Also crash on mp_legacy, mp_atlantis
