### ISSUE TITLE
Demos: autorecord

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#177]
Start recording when a player initially spawns
Pause this recording when a player goes spectate or starts watching another demo

**Comment by iznogod** [comment]
Just give demos their runid as an int instead of their name, can match that to a player easily enough.

Gimme a demo handle back isntead of per-playering it

**Comment by Yocairo** [comment]
Yeah I will, btw is runId unique globally across players?

**Comment by iznogod** [comment]
runid is globaly unique
