### ISSUE TITLE
Runs menu to spawn in a specific run or start new

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#183]
- don't automatically spawn anymore? (Otherwise a new run is created that the player may not want) or it would be even better if there is an option to spawn them with the menu open but don't start a run until they selected something?

- show all runs in menu
- show "new run" option
- allow run deletion
- when clicking on a run, set their spectator origin to the run but keep the menu open

Also allow menu to be opened from !runs and from escape menu.

**Comment by iznogod** [comment]
Runs are from database, so if you make them on-demand there's gonna be some lag when you dont have the db and the slave server on the same continent, so just creating a run (one int) is probably fine.

Why limit the amount of runs to 10? Just allow players to tag their runs and add a search option for strings

Sort by different columns depending on user input (gui)

**Comment by Yocairo** [comment]
I was thinking limit to 10 to make onDemand not lag, as well as allowing demo continuation for runs.

**Comment by Yocairo** [comment]
![image](https://github.com/opencj-dev/server-gsc/assets/26691621/9e3a401b-8d77-46d1-9d30-8b6e31f6258c)

(from izno in Discord, but this isn't complete yet)

**Comment by iznogod** [comment]
tagging/searching runs

**Comment by iznogod** [comment]
Deleting runs/untagging runs

**Comment by Yocairo** [comment]
Pay attention to penalty mentioend in #119

**Comment by Yocairo** [comment]
Basic version implemented, no archiving/tagging/untagging yet, but can at least filter/sort and restore.
