### ISSUE TITLE
Add routes table

### ISSUE THREAD

**Issue by iznogod** [opencj-dev/server-gsc#198]
checkpointID unique
mapid (?) is already in checkpoints
route name
isBonus 1/0

**Comment by iznogod** [comment]
type as enum (normal/bonus/secret/freeroam)
route color here too

**Comment by iznogod** [comment]
difficulty

**Comment by iznogod** [comment]
Added to db, needs gsc update

**Comment by Yocairo** [comment]
@iznogod can you update description? I don't know what needs to be done

**Comment by iznogod** [comment]
i'd have to look into it again too. Is required for alpha though.

**Comment by Yocairo** [comment]
Duplicate of #174
