### ISSUE TITLE
Filterable, sortable records menu (leaderboard)

### ISSUE THREAD

**Issue by Yocairo** [opencj-dev/server-gsc#212]
![image](https://github.com/opencj-dev/server-gsc/assets/26691621/7e7e4f1e-5cc7-440a-9aa2-76e4345ae29f)

![image](https://github.com/opencj-dev/server-gsc/assets/26691621/5676e72d-064f-4ec0-b4cc-53d46c406261)

**Comment by iznogod** [comment]
Dropdowns should be overlays, not pre-set like this since the amount of routes will be too great
Sorting by can be the top of column button instead of a separate menu thing
Maybe put the routes all the way on the left in their own full height column to bypass the amount-of-routes issue?

**Comment by Yocairo** [comment]
Status so far

https://medal.tv/games/cod-4-mw/clips/1mGyneJDZcBuWy/d1337TrHAhCK?invite=cr-MSxLd2IsMTk1ODgxNzQxLA
