### ISSUE TITLE
Advertisement messages (Ridge: please do not... bleh)

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#27]

**Comment by fnkcj** [comment]
I don't think we need these.

**Comment by iznogod** [comment]
Stuff like "join our discord on [url]"?

**Comment by fnkcj** [comment]
We could have an info section somewhere in the settings that has all this stuff. I don't think we need to constantly spam everyone.
Could even make it a command.

**Comment by iznogod** [comment]
Fair. Closed.
