### ISSUE TITLE
Viewbobbing

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#32]

**Comment by fnkcj** [comment]
This needs toggle on/off. For this use command `/bg_bobmax` because this can be changed when doing demo playback (can add/remove bobbing to or from a demo).

**Comment by Yocairo** [comment]
I will just add it as a setting, something like !viewbob <on/off> for now

**Comment by iznogod** [comment]
iirc there were 2 cvars that control this, one for bobbing during run/sprint and one for swaying the gun or smth.

**Comment by Yocairo** [comment]
Gun sway I will do in the weapon_mp, it's just copy paste. For this ticket just bg_bobmax is implemented.
