### ISSUE TITLE
Best records (leaderboard) menu

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#4]

**Comment by Yocairo** [comment]
Gonna need a sketchup from Funk for this one...

**Comment by iznogod** [comment]
Both for the in-menu and in-quickmessage ones.

**Comment by Yocairo** [comment]
Why should there be two leaderboard menus?

**Comment by iznogod** [comment]
The in-menu one would have mouse interaction enabled, the quickmessage one just provides a few (pre-selected) records at a glance during a run.

**Comment by Yocairo** [comment]
@funk what do you think, would there be any value to that in CoD4? I feel like it's kind of unnecessary to have 2 menus personally.

**Comment by fnkcj** [comment]
Agree with @Yocairo.

Two menus are not necessary imo.

**Comment by Yocairo** [comment]
Duplicate of #212
