### ISSUE TITLE
Multi-route checkpoints with different colors/icons

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#6]

**Comment by iznogod** [comment]
Reverse pathfinding for tagging checkpoints for their ender(s). Multiple enders possible. Gsc-based script.

**Comment by iznogod** [comment]
Reverse pathfinding done. Needs different icons.

**Comment by iznogod** [comment]
Should be fully implemented, needs icons and per-route settings in db

**Comment by iznogod** [comment]
Done, although needs db updates

**Comment by iznogod** [comment]
udpate checkpointpointers oninit for more colors

**Comment by Yocairo** [comment]
all enders converted to lowercase
easy,inter,inter+,hard,advanced are colored

**Comment by fnkcj** [comment]
Possible to select certain colors for certain routes? For example if an inter way has a yellow theme, it feels weird to have a blue default inter color there. Checkpoint colors should be in line with the main colortheme of the route.

**Comment by Yocairo** [comment]
Yes, I just did all easy/inter/hard/advanced for now, but if we see a map has specific colors, we can write those to database instead.

**Comment by iznogod** [comment]
Closed. Per-map settings shoudl be its own issue.
