### ISSUE TITLE
Noclip with customizable speed

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#65]

**Comment by fnkcj** [comment]
This would be nice for both normal noclip and also fast noclip (while aiming or sprinting). So I could set how fast (or slow) both modes are, instead of the fast mode being just a flat multiplier to the default noclip speed.

**Comment by iznogod** [comment]
Would become inconvenient to have both speeds set manually imo, scaling seems better so you only need to !noclip or !noclip 10 or whatever

**Comment by Yocairo** [comment]
I'm closing this ticket, as the original implementation of customizable speed is complete.
I think customizing both the speeds would make it confusing and I don't think it's needed. If players end up really desiring this, we can always choose to do it later.
