### ISSUE TITLE
Checkpoints on minimap as objective

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#67]

**Comment by iznogod** [comment]
Done for cod2

**Comment by iznogod** [comment]
For cod4x: hook at start of clientendframe

;ClientEndFrame(gentity_s*)
ClientEndFrame:
	push ebp
	mov ebp, esp
	push edi
	push esi
	push ebx
	sub esp, 0xac
	mov eax, [ebp+0x8]
	mov eax, [eax+0x15c]
	mov [ebp-0x70], eax
	mov edx, [ebp+0x8]
	mov byte [edx+0x16e], 0xb
	mov dword [eax+0x89c], 0x0
	mov ecx, [ebp-0x70]
	mov eax, [eax+0x2ffc]
	mov [ecx+0x5dc], eax
	mov eax, [ecx+0x3080]
	test eax, eax
	jz ClientEndFrame_10

**Comment by iznogod** [comment]
According to iBuddie, at the start of SV_SendClientMessages should also work, which is not an asm func

**Comment by iznogod** [comment]
Done. Done. Done.
